models/__init__.py
from .post import Post
from .user import User

models/post.py
# 檔名：models/post.py
from sqlalchemy import Integer, String, Text, ForeignKey
from sqlalchemy.orm import mapped_column, relationship
from sqlalchemy.sql import func
from config.setting import db
from .mixins.datetime import TimeTrackable


class Post(db.Model, TimeTrackable):
    __tablename__ = "posts"

    id = mapped_column(Integer, primary_key=True)
    title = mapped_column(String, nullable=False)
    content = mapped_column(Text)
    user_id = mapped_column(
        Integer, ForeignKey("users.id", name="fk_post_to_user_id"), nullable=False
    )
    author = relationship("User", back_populates="posts")

    def __repr__(self):
        return f"{self.title}"
    

models/user.py
from sqlalchemy import Integer, String, Text, DateTime
from sqlalchemy.orm import mapped_column, relationship
from sqlalchemy.sql import func
from config.setting import db
from .mixins.datetime import TimeTrackable
from flask_login import UserMixin
    



class User(db.Model, TimeTrackable, UserMixin):
    __tablename__ = "users"

    id = mapped_column(Integer, primary_key=True)
    username = mapped_column(String(50), nullable=False)
    password = mapped_column(String(100), nullable=False)

    posts = relationship("Post", back_populates="author")

    def __repr__(self):
        return f"{self.username}"

apps/post/forms.py
from flask_wtf import Form
from wtforms import StringField, TextAreaField
from wtforms.validators import InputRequired

STYLES = "text-xl w-full md:w-1/2 p-2 border border-gray-900 rounded-sm"

class PostForm(Form):
    title = StringField(
        "標題",
        validators=[InputRequired()],
        render_kw={"placeholder": "請填寫標題", "class": STYLES},
    )
    content = TextAreaField(
        "內文", render_kw={"placeholder": "文章內容", "class": STYLES}
    )

apps/user/forms.py
from flask_wtf import Form
from wtforms import StringField, PasswordField
from wtforms.validators import InputRequired, Length, EqualTo, ValidationError
from models.user import User
# 表單驗證

STYLES = "text-xl w-full md:w-1/2 px-3 py-2 border border-gray-900 rounded-sm"

def unique_username(form, field):
    if User.query.filter_by(username=field.data).first():
        raise ValidationError("該帳號已被申請過!")

class UserRegisterForm(Form):
    username = StringField("帳號",
                           validators=[InputRequired(), Length(min=4), unique_username],
                           render_kw={"placeholder": "使用者帳號", "class": STYLES},)
    
    password = PasswordField("密碼",
                             validators=[InputRequired(), Length(min=4)],
                             render_kw={"placeholder": "請填寫密碼", "class": STYLES},)
    
    password_confirm = PasswordField("密碼確認",
                                     validators=[InputRequired(), EqualTo("password", message="密碼不符")],
                                     render_kw={"placeholder": "再次確認密碼", "class": STYLES},)
    

class UserLoginForm(Form):
    username = StringField("帳號",
                           validators=[InputRequired(), Length(min=4)],
                           render_kw={"placeholder": "使用者帳號", "class": STYLES},
                           )
    password = PasswordField("密碼",
                             validators=[InputRequired()],
                             render_kw={"placeholder": "登入密碼", "class": STYLES},
                             )

app.py
from config.setting import db
from flask_migrate import Migrate
from apps.post.views import post_bp, index as root_view
from apps.error.handlers import error_bp
from apps.user.views import user_bp
from apps import app


app.add_url_rule("/", view_func=root_view, endpoint="root")
app.register_blueprint(post_bp, url_prefix="/posts")
app.register_blueprint(error_bp)
app.register_blueprint(user_bp, url_prefix="/users")

db.init_app(app)
Migrate(app, db)



if __name__ == "__main__":
    app.run(debug=True)

apps/__init__.py
from flask import Flask
from dotenv import load_dotenv
import os
from pathlib import Path
from flask_login import LoginManager
from models import User


# 載入環境變數
load_dotenv()

ROOT_PATH = Path().parent.absolute()
TEMPLATE_FOLDER = ROOT_PATH / "templates"
DB_PATH = ROOT_PATH / "db" / "blog.db"

app = Flask(__name__, template_folder=TEMPLATE_FOLDER)
app.config["SQLALCHEMY_DATABASE_URI"] = f"sqlite:///{DB_PATH}"

# 從環境變數讀取 SECRET KEY
app.secret_key = os.getenv("APP_SECRET_KEY")

login_manager = LoginManager()
login_manager.init_app(app)
login_manager.login_view = "user.login"
login_manager.login_message = "請登入會員帳號"

@login_manager.user_loader
def load_user(id):
    return User.query.get(id)

apps/post/views.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from models import Post
from config.setting import db
from flask_login import login_required, current_user
from .forms import PostForm

post_bp = Blueprint("post", __name__)

@post_bp.route("/")
def index():
    posts = Post.query.order_by(-Post.id).all() # 相等於 posts = models.Post.query.order_by(models.Post.id.desc()).all()
    return render_template("posts/index.html", posts=posts)



@post_bp.route("/new")
@login_required
def new():
    form = PostForm()
    return render_template("posts/news.html", form=form)

@post_bp.route("/create", methods=["POST"])
@login_required
def create():
    form = PostForm(request.form)
    
    if form.validate():
        # 從前端獲取資料
        title = form.title.data
        content = form.content.data

        post = Post(title=title, content=content)

        post.author = current_user
        
        # 寫入 DB
        db.session.add(post)
        db.session.commit()
        
        # 設定快閃訊息
        flash("新增文章成功!")

        # 表單按下送出後自動跳回首頁
        return redirect(url_for("post.index"))
    return render_template("posts/news.html", form=form)

@post_bp.route("/<int:id>")
def show(id):
    post = Post.query.get_or_404(id)
    return render_template("posts/show.html", post=post)


@post_bp.route("/<int:id>/edit")
@login_required
def edit(id):
    post = Post.query.filter_by(id=id, author=current_user).first_or_404()
    form = PostForm(obj=post)
    return render_template("posts/edit.html", post=post, form=form)

@post_bp.route("/<int:id>/update", methods=["POST"])
@login_required
def update(id):
    post = Post.query.filter_by(id=id, author=current_user).first_or_404()
    form = PostForm(request.form, obj=post)

    if form.validate():
        form.populate_obj(post)
        
        # 寫入 DB
        
        db.session.commit()
        
        # 快閃訊息
        flash("文章更新成功")
        
        return redirect(url_for("post.show", id=id))
    return render_template("/posts/edit.html", post=post, form=form)

@post_bp.route("/<int:id>/deltet", methods=["POST"])
@login_required
def delete(id):
    post = Post.query.filter_by(id=id, author=current_user).first_or_404()

    db.session.delete(post)
    db.session.commit()

    flash("文章已刪除")

    return redirect(url_for("post.index"))

apps/user/views.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from .forms import UserRegisterForm, UserLoginForm
from config.setting import db
from models import User
from apps import app
from flask_bcrypt import Bcrypt
from flask_login import login_user, logout_user

user_bp = Blueprint("user", __name__)
bcrypt = Bcrypt(app)

@user_bp.route("/sign_up")
def new():
    form = UserRegisterForm()
    return render_template("users/news.html", form=form)

@user_bp.route("/create", methods=["POST"])
def create():
    form = UserRegisterForm(request.form)

    if form.validate():
        hashed_password = bcrypt.generate_password_hash(form.password.data)
        user = User(username=form.username.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash("註冊成功")
        return redirect(url_for("root"))
    
    return render_template("users/news.html", form=form)

@user_bp.route("/login", methods=["GET", "POST"])
def login():
    form = UserLoginForm(request.form)
    if request.method == "POST" and form.validate():
        user = User.query.filter_by(username=form.username.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user)
            flash("登入成功!")
            return redirect(url_for("root"))
        else:
            flash("帳號或密碼錯誤!請確認後再重試一次")
    return render_template("users/login.html", form=form)

@user_bp.route("/logout", methods=["POST"])
def logout():
    logout_user()
    flash("已登出!")
    return redirect(url_for("root"))

templates/helpers/form_field.html
{% macro render_field(field) %}
<div class="flex flex-col gap-2">
  {{ field.label(class="font-bold") }} {{ field(**kwargs)|safe }} {% if
  field.errors %}
  <ul>
    {% for error in field.errors %}
    <li class="px-1 font-bold text-red-500">{{ error }}</li>
    {% endfor %}
  </ul>
  {% endif %}
</div>
{% endmacro %}

templates/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <script src="https://cdn.tailwindcss.com"></script>
    <title>Simple Blog</title>
  </head>
  <body>
    <main class="container p-12 mx-auto my-4 bg-white rounded shadow">
      {% include "shared/flash.html" %} {% include "shared/navbar.html" %} {%
      block content %}{% endblock %}
    </main>
  </body>
</html>

templates/posts/edit.html
{% extends "layout.html" %} {% from "helpers/form_field.html" import
render_field %} {% block content %}

<h1 class="text-2xl mb-2">更新文章</h1>
<form
  action="{{ url_for('post.update', id=post.id) }}"
  method="POST"
  class="flex flex-col gap-4"
>
  {{ render_field(form.title) }} {{ render_field(form.content, row=6) }}
  <div>
    <button type="submit" class="text-lg bg-blue-500 text-white p-2 rounded-sm">
      更新文章
    </button>
  </div>
</form>

{% endblock %}

templates/posts/index.html
{% extends "layout.html" %} {% block content %}
<h1 class="text-3xl">Hello World</h1>

<section class="flex flex-col gap-4 mt-2">
  {% for post in posts %}
  <div>
    <header class="my-1">
      <h2 class="text-lg font-bold">
        <a href="{{ url_for('post.show', id=post.id) }}">{{ post.title }}</a>
      </h2>
    </header>
    <article class="flex flex-col gap-2 p-2 bg-slate-50">
      <time
        datetime="{{ post.created_at.isoformat() }}"
        class="text-xs text-slate-500"
      >
        {{ post.created_at.strftime('%Y-%m-%d') }}
      </time>
      <p>{{ post.content }}</p>
    </article>
  </div>
  {% endfor %}
</section>
{% endblock %}

templates/posts/news.html
{% extends "layout.html" %} {% from "helpers/form_field.html" import
render_field %} {% block content %}

<h1 class="mb-2 text-2xl">新增文章</h1>
<form action="/posts/create" method="post" class="flex flex-col gap-4">
  {{ render_field(form.title) }} {{ render_field(form.content, row=6) }}
  <div>
    <button
      type="submit"
      class="p-2 text-lg text-white bg-blue-500 rounded-sum"
    >
      新增文章
    </button>
  </div>
</form>
{% endblock %}

templates/posts/show.html
{% extends "layout.html" %} {% block content %}
<h1 class="text-2xl">{{ post.title }}</h1>
<article>
  <time
    datetime="{{ post.created_at.isoformat() }}"
    class="text-xs text-slate-500"
  >
    {{ post.created_at.strftime('%Y-%m-%d') }}
  </time>
  <p class="px-4 py-2 bg-gray-50">{{ post.content }}</p>
</article>
<footer class="flex gap-2 my-1">
  <a
    href="{{ url_for('post.edit', id=post.id) }}"
    class="inline-block px-2 py-1 text-white bg-green-400"
    >編輯
  </a>

  <form
    action="{{ url_for('post.delete', id=post.id)}}"
    method="post"
    onsubmit="return confirm('確認刪除')"
  >
    <button class="px-2 py-1 text-white bg-red-400 select-none">刪除</button>
  </form>
</footer>
{% endblock %}

templates/shared/flash.html
{% with messages = get_flashed_messages() %} {% if messages %}
<div class="px-4 py-2 text-lg text-white bg-orange-500 rounded-sm select-none">
  <ul>
    {% for message in messages %}
    <li>{{ message }}</li>
    {% endfor %}
  </ul>
</div>
{% endif %} {% endwith %}

templates/shared/navbar.html
<nav class="flex items-center justify-between my-2">
  <ul class="flex gap-4">
    <li>
      <a href="/" class="hover:underline">文章列表</a>
    </li>
    <li>
      <a href="/posts/new" class="hover:underline">新增文章</a>
    </li>
  </ul>
  <ul class="flex gap-4">
    {% if current_user.is_authenticated %}
    <li>{{ current_user }}</li>
    <li>
      <form action="{{ url_for('user.logout') }}" method="post">
        <button class="hover:underline">登出</button>
      </form>
    </li>
    {% else %}
    <li>
      <a href="{{ url_for('user.new') }}" class="hover:underline">註冊</a>
    </li>
    <li>
      <a href="{{ url_for('user.login') }}" class="hover:underline">登入</a>
    </li>
    {% endif %}
  </ul>
</nav>

templates/users/login.html
{% extends "layout.html" %} {% from "helpers/form_field.html" import
render_field %} {% block content %}
<h1 class="mb-2 text-2xl">會員登入</h1>
<form
  action="{{ url_for('user.login') }}"
  method="post"
  class="flex flex-col gap-4"
>
  {{ render_field(form.username) }} {{ render_field(form.password) }}
  <div>
    <button type="submit" class="p-2 text-lg text-white bg-blue-500 rounded-sm">
      登入
    </button>
  </div>
</form>
{% endblock %}

templates/users/news.html
{% extends "layout.html" %} {% from "helpers/form_field.html" import
render_field %} {% block content %}

<h1 class="mb-2 text-2xl">會員註冊</h1>
<form
  action="{{ url_for('user.create') }}"
  method="post"
  class="flex flex-col gap-4"
  onsubmit="return confirm('確認送出')"
>
  {{ render_field(form.username) }} {{ render_field(form.password) }} {{
  render_field(form.password_confirm) }}
  <div>
    <button type="submit" class="p-2 text-lg text-white bg-blue-500 rounded-sm">
      註冊帳號
    </button>
  </div>
</form>

{% endblock %}